conteudos/urls.py
from django.urls import path

from . import views

app_name = 'conteudos'

urlpatterns = [
    path('', views.pageConteudos.as_view(), name="conteudos"), 
    path('especialista/', views.pageTreinamentoEspecialista.as_view(), name="especialista"), 
    path('gerenteRede/', views.pageTreinamentoGerenteRede.as_view(), name="gerenteRede"), 
    path('gerenteLoja/', views.pageTreinamentoGerenteLoja.as_view(), name="gerenteLoja"), 
    path('<slug>', views.pageDetalheFuncionalidades.as_view(), name="detalhe_funcionalidade_especialista"), 
    path('<slug>', views.pageDetalheFuncionalidades.as_view(), name="detalhe_funcionalidade_gerenteRede"), 
    path('<slug>', views.pageDetalheFuncionalidades.as_view(), name="detalhe_funcionalidade_gerenteLoja"), 
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homePage.as_view(), name="home"), 
    path('eventos/', views.listaEventos.as_view(), name="eventos"),
    path('projetos/', views.listaProjetos.as_view(), name="projetos"),
    path('sobre/', views.informacoesSobre.as_view(), name="sobre"),
    path('aulas/', views.informacoesAulas.as_view(), name="aulas"),
    path('contato/', views.informacoesContato, name="contato"),
    path('<slug>', views.detalhePost.as_view(), name="detalhe"),
    

    path('como_comprar/', views.informacoesComoComprar.as_view(), name="como_comprar"),
    path('pagamento_e_envio/', views.informacoesPagamentoEnvio.as_view(), name="pagamento_e_envio"),
    path('seguranca/', views.informacoesSeguranca.as_view(), name="seguranca"),
    path('frete/', views.informacoesFrete.as_view(), name="frete"),
    path('trocas_e_devolucoes/', views.informacoesTrocasDevulucoes.as_view(), name="trocas_e_devolucoes"),
    path('garantia/', views.informacoesGarantia.as_view(), name="garantia"),
    path('termos_de_uso/', views.informacoesTermosUso.as_view(), name="termos_de_uso"),
    path('politica_de_privacidade/', views.informacoesPoliticaPrivacidade.as_view(), name="politica_de_privacidade"),
    path('aviso_legal/', views.informacoesAvisoLegal.as_view(), name="aviso_legal"),
    path('documentacao/', views.informacoesDocumentacao.as_view(), name="documentacao"),
]

loja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('contato/', include('contato.urls')),
    path('aulas/', include('aulas.urls')),
    path('produto/', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('suporte/', include('suporte.urls')),
    path('conteudos/', include('conteudos.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conteudos/models.py
import os
from tkinter import image_names

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from PIL import Image

from aulas.models import Aulas
from contato.models import Contato
from produto.models import Produto
from utils import utils


class Funcionalidades(models.Model):
    data_post = models.DateTimeField(default=timezone.now, verbose_name='Data')
    exibir_funcionalidade = models.BooleanField(default=True, verbose_name='Exibir esta funcionalidade?')
    funcionalidade_especialista = models.BooleanField(default=False, verbose_name='Funcionalidade de Especialista?')
    funcionalidade_GerenteLoja = models.BooleanField(default=False, verbose_name='Funcionalidade de Gerente de Loja?')
    funcionalidade_GerenteRede = models.BooleanField(default=False, verbose_name='funcionalidade de Gerente de rede?')
    titulo_funcionalidade = models.CharField(max_length=255, verbose_name='Título da funiocnalidade')
    subtitulo_funcionalidade = models.CharField(max_length=255, verbose_name='Sub-título da funcionalidade')
    autor_publicacao = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Autor da publicação')
    conteudo_funcionalidade = models.TextField(verbose_name='Conteúdo')
    icone_funcionalidade = models.ImageField(upload_to='post_img/%Y/%m/%d', blank=True,
                                    null=True, verbose_name='Imagem do icone da funcionalidade')
    slug = models.SlugField(unique=True, blank=True, null=True, verbose_name='Slug do final do link')
    
    def __str__(self):
        return self.titulo_funcionalidade

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.icone_funcionalidade:
            self.resize_image(self.icone_funcionalidade.name, 800)

    @staticmethod
    def resize_image(img_name, new_width):
        img_path = os.path.join(settings.MEDIA_ROOT, img_name)
        img = Image.open(img_path)
        width, height = img.size
        new_height = round((new_width * height) / width)

        if width <= new_width:
            img.close()
            return

        new_img = img.resize((new_width, new_height), Image.ANTIALIAS)
        new_img.save(
            img_path,
            optimize=True,
            quality=60
        )
        new_img.close()

conteudos/views.py
from dataclasses import fields
from mailbox import NotEmptyError
from re import template
from urllib import request

from django.contrib import messages
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.db.models import Q
from django.forms import ModelForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

import suporte
from contato.views import formulario_contato
from conteudos.admin import FuncionalidadesAdmin
from conteudos.models import Funcionalidades
from home.admin import ContatoAdmin
from home.models import FormularioContato
from perfil.models import Perfil
from produto.models import Produto
from suporte import models


# Create your views here.
class pageConteudos(ListView):
    model = models.Aulas
    template_name = 'conteudos/conteudos.html'

class pageTreinamentoEspecialista(ListView):
    model = Funcionalidades
    template_name = 'conteudos/especialista.html'
    context_object_name = 'funcionalidade'
    paginate_by = 6
    ordering = ['-id']

class pageDetalheFuncionalidades(DetailView):
    model = Funcionalidades
    template_name = 'conteudos/detalhe_funcionalidade_especialista.html'
    template_name = 'conteudos/detalhe_funcionalidade_gerenteLoja.html'
    template_name = 'conteudos/detalhe_funcionalidade_gerenteRede.html'
    context_object_name = 'funcionalidade'
    slug_url_kwarg = 'slug'
    

class pageTreinamentoGerenteRede(ListView):
    model = Funcionalidades
    context_object_name = 'funcionalidade'
    paginate_by = 6
    ordering = ['-id']
    template_name = 'conteudos/gerenteRede.html'

class pageTreinamentoGerenteLoja(ListView):
    model = models.Aulas
    model = Funcionalidades
    context_object_name = 'funcionalidade'
    paginate_by = 6
    ordering = ['-id']
    template_name = 'conteudos/gerenteLoja.html'

conteudos/templates/conteudos/conteudos.html
<!doctype html>
<html lang="pt-BR">
{%load crispy_forms_tags%}
{% load static %}
{% load omfilters %}

<head>
    {% include 'parciais/_head.html' %}
    <title>{% block titulo %}{% endblock %} CheckApp | Conteudos</title>

    <style>
        :root{
            --green:#27ae60;
            --black:#192a56;
            --blue:#041562;
            --light-color:#666;
            --box-shadow:0 .5rem 1.5rem rgba(0,0,0,.1);
        }
        html{
            font-size: 62.5%;
            overflow-x: hidden;
            scroll-behavior: smooth;
            scroll-padding-top: 8rem;
        }
        
        ::-webkit-scrollbar{
            height: .5rem;
            width: 1rem;
        }
        
        ::-webkit-scrollbar-track{
            background-color: transparent;
        }
        
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        .navCarrinhoVazio{
            display: flex;
        }
        .icone-btb-LojaOnline{
            margin: 10px;
        }

        .formularioContato .tabelaFormularioContato .td-tabelaFormularioContato input{
            background-color: #f3d600;
            border: 1px #f3d600 solid;
            color: black;
            padding: 8px 0px;
            width: 200px;
            height: 50px;
            display: flex;
            border-radius: 50px;
            place-content: center;
            font-weight: 800;
            cursor: pointer;
            max-width: 265px;
            align-items: center;
            margin-top: 20px;
        }
        .formularioContato .tabelaFormularioContato .td-tabelaFormularioContato input:hover{
            background-color: #ffd40d;
            color: black;
        }
    
        #container-contato-suporte{
            background-color: white;
            height: 1000px;
            border-radius: 50px;
            margin-top: 40px;
        }
        .tituloFormularioContato{
            font-size: 24px;
            font-weight: 500;
            color: white;
            text-align: initial;
            margin: 20px 0px 8px 0px;
        }
        .linhaDecorativaFormulario-contato{
            width: 300px;
            height: 5px;
            display: flex;
            background-color: #f3d600;
            margin: 0px 0px 30px 0px;
        }
        .efeito::after{
            content:'|';
            color: red;
            margin-left: 5px;
            opacity: 10;
            animation: escrevendo .7s infinite;
        }
        .mensagensFormulario{
            display: flex;
            width: 100%;
            height: 50px;
            margin-top: 12px;
            position: absolute;
            justify-content: center;
        }
        .mensagensFormulario .alert{
            padding: 0.75rem 25.25rem !important;
            font-size: 20px !important;
            font-family: dosis;
            display: flex;
        }
        .formulario-contato-suporte{
            background: black !important;
            border-radius: 50px;
            width: 50%;
            height: 100%;
            padding: 50px;
        }

        .formularioContato label{
            color: white !important;
            font-size: 15px;
            

        }
        .formularioContato input{
            font-size: 20px;
           
        }
        .containerSuporteCliente{
            padding: 0px 80px;
            width: 80%;
            margin: 0px 211px;
            display: block;
        }
        .mensagemSuporte{
            width: 100%;
            position: sticky;
        }
        .tituloSuporte{
            display: block;
            text-align-last: initial;
            
        }
        .navSuporte{
            display: flex;
            text-align-last: initial;
            
        }
        .sectionSuporte{
            margin: 60px 0px;
        }
        .sectionConteudos{
            display: flex;
            width: 100%;

        }
        .cardsConteudos{
            display: flex;
            width: 100%;
            height: 100%;
        }
        .cardItemConteudo{
            background: #1e1e1e;
            border-radius: 50px;
            width: 350px;
            height: 250px;
            margin: 15px 15px 0px;
            display: flex;
            place-content: center;

        }
        .treinamentoEspecialista{
            background: #ff0000;
        }
        .treinamentoGerenteLoja{
            background: #ff0000;
    
        }
        .treinamentoGerenteRede{
            background: #f9df00;
        }
      
        .img-conteudo1{
            padding: 0px 170px;
            height: 260px;
            display: flex;
            text-align: -webkit-center;
            background-image: url(/media/imagens/rede.jpg);    
            background-repeat: no-repeat;
            background-position: right;
            background-size: 150%;
            text-decoration: none !important;
           
        }
        .img-conteudo1:hover{
            background-size: 120%;
        }
        .img-conteudo2{
            padding: 0px 170px;
            height: 260px;
            display: flex;
            text-align: -webkit-center;
            background-image: url(/media/imagens/loja.jpg);    
            background-repeat: no-repeat;
            background-size: 150%;
            text-decoration: none !important;
           
        }
        .img-conteudo2:hover{
            background-size: 120%;
        }
        .img-conteudo3{
            padding: 0px 170px;
            height: 260px;
            display: flex;
            text-align: -webkit-center;
            background-image: url(/media/imagens/pista.jpg);
            background-repeat: no-repeat;
            background-position: right;
            background-size: 110%;
            text-decoration: none !important;
           
    
        }
        .img-conteudo3:hover{
            background-size: 120%;
        }
        @media screen and (max-width: 1200px) {
    
            .cardsConteudos{
                display: block !important;
            }
            .containerConteudos{
                padding: 0px 100px;
            }

        }
        @media screen and (max-width: 800px) {
            .containerConteudos{
                padding: 0px 30px;
            }
            .sectionConteudos {
                text-align: -webkit-center;
            }

        }
        .textosCardsTreinamentos{
            display: block;
            align-self: center;

        }
        .texto-fundoBranco{
            background-color: white !important;
            max-width: 180px !important;
            min-width: 100px !important;
            min-height: 55px !important;
            max-height: 55px !important;
            color: #ff0000;
            border-radius: 16px;
            text-decoration: none !important;
            padding: 5px;
            
        }

    </style>

</head>



{% load omfilters %}


{% include 'parciais/_menulateral.html' %}

<div class="container containerConteudos">
    <section class="sectionSuporte">
        <div class="container-suporte">
            <div class="navSuporte">
                <i class='bx bx-chalkboard iconeSuporte icon'></i>
                <span class="textos textoBranco tituloPage">Conteudos</span>
            </div>

            <br><br>
            <div class="tituloSuporte">
                <p class="titulo1 texto-amarelo">Tutoriais de treinamento e utilização</p>
                <br>
                <p class="textos textoBranco">Conheça nossas funcionalidades através de vídeos, selecione o módulo desejado a baixo:</p>
            </div>
            <br><br><br>

            <section class="sectionConteudos">
                <div class="cardsConteudos">
                    <a href="{% url 'conteudos:gerenteRede'  %}" class="cardItemConteudo treinamentoEspecialista img-conteudo1">
                        <div class="textosCardsTreinamentos">
                            <p class="textos textoBranco">Treinamento</p>
                            <p class="textos textoBranco"> Módulo</p>
                            <p class="textos textoBranco texto-fundoBranco">REDE</p>
                        </div>
                    </a>
                    <a href="{% url 'conteudos:gerenteLoja' %}" class="cardItemConteudo TreinamentoGerenteLoja img-conteudo2">
                        <div class="textosCardsTreinamentos">
                            <p class="textos textoBranco">Treinamento</p>
                            <p class="textos textoBranco"> Módulo</p>
                            <p class="textos textoBranco texto-fundoBranco">LOJA</p>
                        </div>
                    </a>
                    <a href="{% url 'conteudos:especialista' %}" class="cardItemConteudo TreinamentoGerenteRede img-conteudo3">
                        <div class="textosCardsTreinamentos">
                            <p class="textos textoBranco">Treinamento</p>
                            <p class="textos textoBranco"> Módulo</p>
                            <p class="textos textoBranco texto-fundoBranco">PISTA</p>
                        </div>
                    </a>
                </div>

            </section>
            
    
        </div>    
    </section>
</div>
<br><br><br>

conteudos/templates/conteudos/detalhe_funcionalidade_especialista.html
<!doctype html>
<html lang="pt-BR">
{%load crispy_forms_tags%}
{% load static %}
{% load omfilters %}

<head>
    {% include 'parciais/_head.html' %}
    <title>{% block titulo %}{% endblock %} CheckApp | Conteudos | Funcionalidades | Especialista | Detalhes</title>

    <style>
        :root{
            --green:#27ae60;
            --black:#192a56;
            --blue:#041562;
            --light-color:#666;
            --box-shadow:0 .5rem 1.5rem rgba(0,0,0,.1);
        }
        html{
            font-size: 62.5%;
            overflow-x: hidden;
            scroll-behavior: smooth;
            scroll-padding-top: 8rem;
        }
        
        ::-webkit-scrollbar{
            height: .5rem;
            width: 1rem;
        }
        
        ::-webkit-scrollbar-track{
            background-color: transparent;
        }
        
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        .navCarrinhoVazio{
            display: flex;
        }
        .icone-btb-LojaOnline{
            margin: 10px;
        }

        .formularioContato .tabelaFormularioContato .td-tabelaFormularioContato input{
            background-color: #f3d600;
            border: 1px #f3d600 solid;
            color: black;
            padding: 8px 0px;
            width: 200px;
            height: 50px;
            display: flex;
            border-radius: 50px;
            place-content: center;
            font-weight: 800;
            cursor: pointer;
            max-width: 265px;
            align-items: center;
            margin-top: 20px;
        }
        .formularioContato .tabelaFormularioContato .td-tabelaFormularioContato input:hover{
            background-color: #ffd40d;
            color: black;
        }
    
        #container-contato-suporte{
            background-color: white;
            height: 1000px;
            border-radius: 50px;
            margin-top: 40px;
        }
        .tituloFormularioContato{
            font-size: 24px;
            font-weight: 500;
            color: white;
            text-align: initial;
            margin: 20px 0px 8px 0px;
        }
        .linhaDecorativaFormulario-contato{
            width: 300px;
            height: 5px;
            display: flex;
            background-color: #f3d600;
            margin: 0px 0px 30px 0px;
        }
        .efeito::after{
            content:'|';
            color: red;
            margin-left: 5px;
            opacity: 10;
            animation: escrevendo .7s infinite;
        }
        .mensagensFormulario{
            display: flex;
            width: 100%;
            height: 50px;
            margin-top: 12px;
            position: absolute;
            justify-content: center;
        }
        .mensagensFormulario .alert{
            padding: 0.75rem 25.25rem !important;
            font-size: 20px !important;
            font-family: dosis;
            display: flex;
        }
        .formulario-contato-suporte{
            background: black !important;
            border-radius: 50px;
            width: 50%;
            height: 100%;
            padding: 50px;
        }

        .formularioContato label{
            color: white !important;
            font-size: 15px;
            

        }
        .formularioContato input{
            font-size: 20px;
           
        }
        .containerSuporteCliente{
            padding: 0px 80px;
            width: 80%;
            margin: 0px 211px;
            display: block;
        }
        .mensagemSuporte{
            width: 100%;
            position: sticky;
        }
        .tituloSuporte{
            display: block;
            text-align-last: initial;
            
        }
        .navFuncionalidade{
            display: flex;
            text-align-last: initial;
            width: 90%;
            
        }
        .sectionSuporte{
            margin: 60px 0px;
        }
        .sectionConteudosEspecialista{
            display: flex;
            width: 100%;

        }
        .navCapaEspecialista{
            display: flex;
            width: 100%;
        }

        .conteudoEspecialista{
            width: 50%;
        }
        .backgroundEspecilsta{
            width: 50%;
            display: flex;
            text-align: -webkit-center;
            background-image: url(/media/imagens/art-celularCheckapp.svg);    
            background-repeat: no-repeat;
            background-size: 70%;
            background-repeat: no-repeat;
            background-position: right;
            margin-top: -270px;
        }
        .listaFuncionalidade{
            width: 100%;
            display: flex;
        }
        .listaFuncionalidade ul{
            width: 100%;
            display: block;
        }

        .listaFuncionalidade li{
            width: 100%;
            display: block;
            margin: 25px 0px;

        }
        .listaFuncionalidade li a{
            
            margin: 25px 0px;

        }
        .cardFuncionalidade{
            display: flex;
            background: white;
            border-radius: 50px;
            width: 100%;
            height: 100%;
            color: black !important;
            text-decoration: none !important;
            padding: 15px 80px 15px 0px;
        }
        .cardFuncionalidade:hover{
            background: #f3d600;
        }
        
        .textosCard{
            width: 80%;
            display: block;
            margin-left: 20px;
        }
        .iconeFuncionalidade{
            width: 20%;
            display: flex;
            justify-content: center;
        }
        .iconeCardFuncionalidade{
            width: 50px;
            height: 50px;
            place-self: center;
        }
        .navDetalheFuncionalidade{
            display: flex;
            justify-content: space-between;
            width: 100%;
            height: 100%;
        }
        .iconeVoltar{
            width: 10%;
            text-align-last: end;
            align-self: center;
            font-size: 30px;

        }
        
        @media screen and (max-width: 800px) {
      
            .note-video-clip{
                width: 100px !important;
                max-width: 100px !important;
            }
        }
    </style>

</head>

{% include 'parciais/_menulateral.html' %}
{%block conteudo%}
<div class="container">
    <section class="sectionSuporte">
        <div class="container-suporte">
            <div class="navDetalheFuncionalidade">
                <div class="navFuncionalidade">
                    <i class='bx bx-chalkboard iconeSuporte icon'></i>
                    <span class="
                    textos textoBranco tituloPage">Conteudos | Módulo Especialista | Tutorial </span>
                </div>
                <div class="iconeVoltar">
                    <a class='bx bxs-arrow-from-right ' href="{% url 'conteudos:conteudos' %}"></a>
                </div>
            </div>

            
            <br><br><br>
            <div class="container">
                <h1 class="titulo1 texto-amarelo">{{ funcionalidade.titulo_funcionalidade }}</h1>
                <br>  
                <h2 class="textos textoBranco">{{ funcionalidade.subtitulo_funcionalidade }}</h2>
                <br>
                <br>
                <section>
                    {{ funcionalidade.conteudo_funcionalidade|safe }}
                </section>   
            </div>  
             
 
        </div>
    </section>
</div>
{%endblock%}
<br><br><br>