home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homePage.as_view(), name="home"), 
    path('eventos/', views.listaEventos.as_view(), name="eventos"),
    path('projetos/', views.listaProjetos.as_view(), name="projetos"),
    path('sobre/', views.informacoesSobre.as_view(), name="sobre"),
    path('aulas/', views.informacoesAulas.as_view(), name="aulas"),
    path('contato/', views.informacoesContato, name="contato"),
    path('<slug>', views.detalhePost.as_view(), name="detalhe"),
    

    path('como_comprar/', views.informacoesComoComprar.as_view(), name="como_comprar"),
    path('pagamento_e_envio/', views.informacoesPagamentoEnvio.as_view(), name="pagamento_e_envio"),
    path('seguranca/', views.informacoesSeguranca.as_view(), name="seguranca"),
    path('frete/', views.informacoesFrete.as_view(), name="frete"),
    path('trocas_e_devolucoes/', views.informacoesTrocasDevulucoes.as_view(), name="trocas_e_devolucoes"),
    path('garantia/', views.informacoesGarantia.as_view(), name="garantia"),
    path('termos_de_uso/', views.informacoesTermosUso.as_view(), name="termos_de_uso"),
    path('politica_de_privacidade/', views.informacoesPoliticaPrivacidade.as_view(), name="politica_de_privacidade"),
    path('aviso_legal/', views.informacoesAvisoLegal.as_view(), name="aviso_legal"),
    path('documentacao/', views.informacoesDocumentacao.as_view(), name="documentacao"),
]

loja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('contato/', include('contato.urls')),
    path('aulas/', include('aulas.urls')),
    path('produto/', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('suporte/', include('suporte.urls')),
    path('conteudos/', include('conteudos.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),

    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),

    path('lista/', views.Lista.as_view(), name='lista'),

    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [

    path('', views.Criar.as_view(), name='criar'),

    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),

    path('login/', views.Login.as_view(), name='login'),

    path('logout/', views.Logout.as_view(), name='logout'),

    path('cadastrar/', views.Cadastrar.as_view(), name='cadastrar'),

    path('acesso/', views.Acesso.as_view(), name='acesso'),

]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostIndex.as_view(), name='index'),
    path('teste', views.teste.as_view(), name='teste'),
    path('oficinas', views.Oficinas.as_view(), name='oficinas'),
    path('categoria/<str:categoria>', views.PostCategoria.as_view(), name='post_categoria'),
    path('estado/<str:estado>', views.PostEstado.as_view(), name='post_estados'),

    path('busca/', views.PostBusca.as_view(), name='post_busca'),
    path('post/<int:pk>', views.PostDetalhes.as_view(), name='post_detalhes'),
]

produto/urls.py
from django.urls import path

from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),

    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),

    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name="adicionaraocarrinho"),

    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name="removerdocarrinho"),

    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),

    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),

    path('busca/', views.Busca.as_view(), name="busca"),

    path('produtos/', views.listaTodosProdutos.as_view(), name="produtos"),

    path('loja/', views.produtosLoja.as_view(), name="loja"),

    path('licencas/', views.listaLicencas.as_view(), name="licencas"),


]

suporte/urls.py
from django.urls import path

from . import views

app_name = 'suporte'

urlpatterns = [

    path('', views.pageSuporte, name='suporte'),



]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User


from django.conf import settings
import os
from PIL import Image
from django.db import models
from django.utils.text import slugify
from utils import utils


class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

home/forms.py
from urllib import request

from contato.models import Contato
from django import forms

from . import views


class Contato(forms.Form):
    nome = forms.CharField(max_length=20)

home/views.py
from dataclasses import fields
from mailbox import NotEmptyError
from re import template
from urllib import request

from django.contrib import messages
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.db.models import Q
from django.forms import ModelForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from contato.views import formulario_contato
from home.admin import ContatoAdmin
from perfil.models import Perfil
from produto.models import Produto

from . import models
from .models import Contato, FormularioContato, Newslatter

# ---- TESTE DE PAGINA -----

#class listaProdutosPizzas(View):
#    def get(self, *args, **kwargs):
#       return HttpResponse('oi')





class homePage(ListView):
    model =  models.Post
    template_name = 'home/home.html'
    context_object_name = 'posts'
    paginate_by = 6
    ordering = ['-id']
    
    

    

    




# ---- LISTAGEM DE EVENTOS E PROJETOS SOCIAIS -----

class listaEventos(ListView):
    model =  models.Post
    template_name = 'home/eventos.html'
    context_object_name = 'posts'
    paginate_by = 6
    ordering = ['-id']


class listaProjetos(ListView):
    model =  models.Post
    template_name = 'home/projetos.html'
    context_object_name = 'posts'
    paginate_by = 10
    ordering = ['-id']



# ---- EXIBIÇÃO DO DETALHE DO POST (projetos sociais e eventos) -----

class detalhePost(DetailView):
    model = models.Post
    template_name = 'home/detalhe.html'
    context_object_name = 'post'
    slug_url_kwarg = 'slug'


# ---- páginas -----

class informacoesSobre(ListView):
    model = models.Post
    template_name = 'home/sobre.html'

class informacoesAulas(ListView):
    model = models.Aulas
    template_name = 'home/aulas.html'
    context_object_name = 'aulas'
    paginate_by = 6
    ordering = ['-id']


def informacoesContato(request):
    if request.method != 'POST':
        form = FormularioContato
        return render(request, 'home/contato.html', {'form': form})

    form = FormularioContato(request.POST)

    if not form.is_valid():
        messages.error(request, 'Erro ao enviar o formulário. Verifique os campos e tente novamente!')
        form = FormularioContato(request.POST)
        return render(request, 'home/contato.html', {'form': form})
    
    nome = request.POST.get('nome')
    telefone = request.POST.get('telefone')
    mensagem = request.POST.get('mensagem')
    
    if len(nome) < 4:
        messages.error(request, 'Nome invalido! Informe um nome com no mínimo 4 caracteres.')
        form = FormularioContato(request.POST)
        return render(request, 'home/contato.html', {'form': form})
    
    if len(telefone) < 8:
        messages.error(request, 'Telefone inválido! Inclua um telefone válido com DD ou acrescente 9 antes do número do telefone.')
        form = FormularioContato(request.POST)
        return render(request, 'home/contato.html', {'form': form})

    if len(mensagem) < 0:
        messages.error(request, 'Descreva o motivo do contato ')
        form = FormularioContato(request.POST)
        return render(request, 'home/contato.html', {'form': form})

    form.save()
    messages.success(request, 'Mensagem enviada com sucesso!')
    return render(request, 'home/contato.html', {'form': form})
    
class informacoesComoComprar(ListView):
    model = models.Post
    template_name = 'home/como_comprar.html'

class informacoesPagamentoEnvio(ListView):
    model = models.Post
    template_name = 'home/pagamento_e_envio.html'

class informacoesSeguranca(ListView):
    model = models.Post
    template_name = 'home/seguranca.html'

class informacoesFrete(ListView):
    model = models.Post
    template_name = 'home/frete.html'

class informacoesTrocasDevulucoes(ListView):
    model = models.Post
    template_name = 'home/trocas_e_devolucoes.html'

class informacoesGarantia(ListView):
    model = models.Post
    template_name = 'home/garantia.html'

class informacoesTermosUso(ListView):
    model = models.Post
    template_name = 'home/termos_de_uso.html'
    
class informacoesPoliticaPrivacidade(ListView):
    model = models.Post
    template_name = 'home/politica_de_privacidade.html'

class informacoesAvisoLegal(ListView):
    model = models.Post
    template_name = 'home/aviso_legal.html'

class informacoesDocumentacao(ListView):
    model = models.Post
    template_name = 'home/documentacao.html'

pedido/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
# from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render
from produto.models import Variacao
from .models import Pedido, ItemPedido


from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from django.db.models import Q

from utils import utils




class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'


class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Seu carrinho está vazio.'
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)

            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
                carrinho[vid]['preco_quantitativo_promocional'] = estoque * \
                    preco_unt_promo

                error_msg_estoque = 'Estoque insuficiente para alguns '\
                    'produtos do seu carrinho. '\
                    'Reduzimos a quantidade desses produtos. Por favor, '\
                    'verifique quais produtos foram afetados a seguir.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )

                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = utils.cart_total_qtd(carrinho)
        valor_total_carrinho = utils.cart_totals(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )

        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del self.request.session['carrinho']

        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']

templates/parciais/_cardapio.html
{% load static %}

    <style>
     @import url('https://fonts.googleapis.com/css2?family=Jua&display=swap');
     @import url('https://fonts.googleapis.com/css2?family=Codystar:wght@300;400&display=swap');
     @import url('https://fonts.googleapis.com/css2?family=Codystar:wght@300;400&family=Rampart+One&display=swap');
     @import url('https://fonts.googleapis.com/css2?family=Codystar:wght@300;400&family=Dancing+Script&family=Rampart+One&display=swap');

    </style>
<body>

  <br><br>

  <!--ACESSO RÁPIDO PARA PRODUTOS-->

  
  <br>
  <br>
  <br>
  <br>
</body>

templates/parciais/_carrinho.html
{% load static %}
{% load omfilters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for linha in carrinho.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
            </td>
            <td>
                <a href="{% url 'produto:detalhe' linha.slug %}">
                    {{ linha.produto_nome }}
                </a>

                <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{ linha.variacao_id }}">
                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{ linha.variacao_nome }}</td>
            <td>
                {{ linha.quantidade }} x
                {% if linha.preco_unitario_promocional %}
                {{ linha.preco_unitario_promocional }}
                {% else %}
                {{ linha.preco_unitario }}
                {% endif %}
            </td>

            {% if linha.preco_quantitativo_promocional %}
            <td>{{ linha.preco_quantitativo_promocional|formata_preco }}</td>
            {% else %}
            <td>{{ linha.preco_quantitativo|formata_preco }}</td>
            {% endif %}

        </tr>
        {% endfor %}


    </table>
</div>

templates/parciais/_footers.html
{% load static %}
<style>
    .logo-checkapp-footer{
        width: 462px;
        height: 200px;
        display: flex;
        background-image: url('/media/imagens/logo.png');
        background-repeat: no-repeat;
        background-size: 300px;
        position: absolute;
    
    }
    .textoSlogan{
        margin-top: 50px !important;
        padding: 0px 30px !important;
    }
    .text-muted{
        font-size: 20px !important;
        font-family: dosis !important;
        

    }
    .texto-topLinks{
        margin-inline-end: auto;
    }
    .texto-pagamentoSeguranca{
        margin-inline-end: auto !important;
    }
    .pagamento-e-redes{
        justify-content: space-between !important;
    }
    .icone-redes-social{
        cursor: pointer;
        font-size: 30px !important;
        color: white !important;
    }
    .icone-redes-social:hover{
        color: red !important;
        list-style-image: none;
    }
    .img-paypal{
        padding: 10px 50px;
        width: 100%;
        height: 100px;
        display: flex;
        text-align: -webkit-center;
        background-image: url('/media/icones/paypal.svg');    
        background-repeat: no-repeat;
        background-size: 80%;
        background-position-x: 20px;
        background-position-y: 7px;
    }
    .img-visa{
        padding: 0px 50px;
        width: 100%;
        height: 100px;
        display: flex;
        text-align: -webkit-center;
        background-image: url('/media/icones/visa.svg');    
        background-repeat: no-repeat;
        background-size: 60%;
        background-position-x: center;
    }
    .img-mastercard{
        padding: 0px 50px;
        width: 100%;
        height: 100px;
        display: flex;
        text-align: -webkit-center;
        background-image: url('/media/icones/mastercard.svg');    
        background-repeat: no-repeat;
        background-size: 60%;
        background-position-x: center;
    }
    .img-pix{
        padding: 0px 50px;
        width: 100%;
        height: 100px;
        display: flex;
        text-align: -webkit-center;
        background-image: url('/media/icones/pix.png');    
        background-repeat: no-repeat;
        background-size: 80%;
        background-position-x: 20px;
        background-position-y: 7px;
    }
    .list-inline-pagamento{
        display: flex;
    }
    .titulos-footer {
        padding: 20px 0px;
    }
    @media screen and (max-width: 500px) {
        .imagemChamadaAcelerar{
            height: 270px !important;
        }
    }
    @media (max-width: 768px) {
        .list-inline-pagamento{
            display: block;
        }
        .textoSlogan{
            padding: 0px 30px !important;
        }
        
    
    }
    @media screen and (max-width: 1150px) {
        .container-action-Register{
            display: block !important;
            height: 850px !important;
        }
    }
    @media screen and (max-width: 800px) {
        .imagemChamadaAcelerar{
            height: 370px !important;
        }
        .containerLinks{
            display: block !important;
        }  
        .containerSuporte{
            margin-top: 30px;
        }
        .container-footers{
            text-align: -webkit-center;
        }
        .logo-checkapp-footer {
            height: 54px;
            background-size: 239px;
            position: inherit;
            margin-left: -25px;
        }
        .iconesRedesSociais{
            margin: 0px 0px !important;
        }
    }
    .row-conteudo-footer{
        margin-left: -58px !important;
        margin-right: -58px !important;
        margin-top: 100px;
        display: flex;
        justify-content: space-between !important;
        
    }
    .containerLinksServicos{
        place-content: end !important;
        
    }
    .titulos-footers{
        font-size: 25px !important;
        font-weight: bolder !important;
        color: #f9df00 !important;
    }
    .iconesRedesSociais{
        transform-origin: center;
        margin: 0px -60px;
    }
    .imagemChamadaAcelerar{
        background-image: url(/media/imagens/recorte-banner.png);
        background-repeat: no-repeat;
        /* background-position-x: 80px; */
        /* background-position-y: -575px; */
        background-size: 100%;
        display: flex;
        width: 74%;
        height: 500px;
    }
    .container-action-Register{
        background-color: #f8df00;
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: space-between;
        height: 500px;
        align-items: center;
    }

    .container-action-Register-action{
        display: block;
        padding: 71px 10px;
        text-align: -webkit-center;
    }

    .container-action-Register-action h2{
        font-family: dosis, sans-serif;
        font-size: 40px;
        font-weight: 900;
        line-height: 40px;
        color: black;
    }
</style>
<br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br>
<footer class=" container-footers pt-5">
    <section class="container-action-Register">


        <div class="imagemChamadaAcelerar">
            
        </div>
        <div class="container-action-Register-action" >
            <h2>
                Pronto para acelerar?
            </h2>
            <br>
            <p class="textos textoPreto">
                A melhor plataforma do setor para turbinar ainda mais gestão da sua oficina.
            </p>            
            <a class="btn btnPreto" href="{% url 'home:sobre' %}">
                SAIBA MAIS
            </a>

        </div>
        
        
        
        

    </section>
    <br><br><br>

	<div class="container">
		<!-- Row START -->
		<div class="row row-conteudo-footer g-4">
            <br><br><br>

			<!-- Widget 1 START -->
			<div class="col-lg-3">
                
				<!-- logo -->
				<div class="logomarca ">
                    <a class="navbar-brand text-logo logo-link " href="{% url 'home:home' %}"> 
                        <h1 class="text-logo logo-checkapp-footer"></h1>
                    </a>
                </div>
                <br><br><br>
				<p class="my-3 texto-amarelo textos textoSlogan ">Oficina digital para vender mais, melhor e para mais clientes.</p>
                <br><br><br>
			</div>
			<!-- Widget 1 END -->

			<!-- Widget 2 START -->
			<div class=" col-lg-8 ms-auto">
				<div class=" containerLinks containerLinksServicos row g-4">
					<!-- Link block -->
					<div class="col-6 col-md-4">
						<h5 class="text-white mb-2 mb-md-4 textos titulos-footers">INSTITUCIONAL</h5>
						<ul class="nav flex-column text-primary-hover">
                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'home:home' %}">Home</a>
                            </li>
                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'perfil:acesso' %}">Login</a>
                            </li>
                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'perfil:criar' %}">Cadastre-se</a>
                            </li>
                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'home:sobre' %}">Sobre</a>
                            </li>
                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'posts:oficinas' %}">Oficinas</a>
                            </li>
                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'home:eventos' %}">Eventos</a>
                            </li>
                        </ul>
					</div>

					<!-- Link block -->
					<div class="containerSuporte col-6 col-md-4">
						<h5 class="text-white mb-2 mb-md-4 titulos-footers textos">SUPORTE</h5>
						<ul class="nav flex-column text-primary-hover">
                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'home:contato' %}">Contato</a>
                            </li>
                            <!--

                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'home:como_comprar' %}">Como comprar</a>
                            </li>
                            -->

                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'home:seguranca' %}">Segurança</a>
                            </li>
                            <li>
                                <a class=" textos ancoraServicos" href="{% url 'home:documentacao' %}">Integração</a>
                            </li>
						</ul>
					</div>
									
				</div>
			</div>
			<!-- Widget 2 END -->

		</div><!-- Row END -->

        <br><br><br><br>

		<!-- Payment and card -->
		<div class="row g-4 pagamento-e-redes mt-0 mt-md-2">

			<!-- Payment card -->
			<div class="col-sm-7 col-md-6 col-lg-4">
				<h5 class="titulos-footer text-white mb-2 texto-pagamentoSeguranca titulos-footers textos">PAGAMENTO &amp; SEGURANÇA</h5>
				<ul class="list-inline list-inline-pagamento mb-0 mt-3">
                    <!--
                    <li class="list-inline-item"> 
                        <a href="#"><i src="#" class="h-5px img-paypal" alt="paypal"></i></a>
                    </li>
                    -->
					
					<li class="list-inline-item"> <a href="#"><i src="#" class="h-5px img-visa" alt="visa"></i></a></li>
					<li class="list-inline-item"> <a href="#"><i src="#" class="h-5px img-mastercard" alt="mastercard"></i></a></li>
					<li class="list-inline-item"> <a href="#"><i src="#" class="h-5px img-pix" alt="pix"></i></a></li>
				</ul>
			</div>

			<!-- Social media icon -->
			<div class="iconesRedesSociais col-sm-5 col-md-6 col-lg-3 text-sm-end">
				<h5 class="titulos-footer mb-2 text-white titulos-footers textos">SIGA-NOS</h5>
				<ul class="list-inline mb-0 mt-3">
					<li class="list-inline-item"> <a class="icone-redes-social bx bxl-facebook" href="https://www.facebook.com/checkapp.net.br"></a> </li>
					<li class="list-inline-item"> <a class="icone-redes-social bx bxl-instagram" href="https://www.instagram.com/checkapp_oficial"></a> </li>
					<li class="list-inline-item">  <a class="icone-redes-social bx bxl-youtube" href="https://www.youtube.com/channel/UCsGwccnjN8Ptsv7y7JvZg2w"></a> </li>
					<li class="list-inline-item"><a class="icone-redes-social bx bxl-whatsapp" href="https://contate.me/checkapp"></a> </li>
				</ul>	
			</div>
		</div>

		<!-- Divider -->
		<hr class="mt-4 mb-0">
        <div class="linhaDecoracao"></div>

		<!-- Bottom footer -->
		<div class="row">
			<div class="container">
				<div class="d-lg-flex justify-content-between align-items-center py-3 text-center text-lg-start">
					<!-- copyright text -->
					<div class="text-muted text-primary-hover"> Copyrights ©2023 | 27.285.525/0001-77 | Todos os direitos reservados</div>
					<!-- copyright links-->
					<div class="nav mt-2 mt-lg-0">
						<ul class="list-inline text-primary-hover mx-auto mb-0">
							<li class="list-inline-item me-0"><a class="nav-link py-1 text-muted"  href="{% url 'home:politica_de_privacidade' %}">Política de privacidade</a></li>
							<li class="list-inline-item me-0"><a class="nav-link py-1 text-muted" href="{% url 'home:termos_de_uso' %}">Termos e condições</a></li>
							<li class="list-inline-item me-0"><a class="nav-link py-1 text-muted pe-0"  href="{% url 'home:aviso_legal' %}">Aviso legal</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>