home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homePage.as_view(), name="home"), 
    path('eventos/', views.listaEventos.as_view(), name="eventos"),
    path('projetos/', views.listaProjetos.as_view(), name="projetos"),
    path('sobre/', views.informacoesSobre.as_view(), name="sobre"),
    path('aulas/', views.informacoesAulas.as_view(), name="aulas"),
    path('contato/', views.informacoesContato, name="contato"),
    path('<slug>', views.detalhePost.as_view(), name="detalhe"),
    

    path('como_comprar/', views.informacoesComoComprar.as_view(), name="como_comprar"),
    path('pagamento_e_envio/', views.informacoesPagamentoEnvio.as_view(), name="pagamento_e_envio"),
    path('seguranca/', views.informacoesSeguranca.as_view(), name="seguranca"),
    path('frete/', views.informacoesFrete.as_view(), name="frete"),
    path('trocas_e_devolucoes/', views.informacoesTrocasDevulucoes.as_view(), name="trocas_e_devolucoes"),
    path('garantia/', views.informacoesGarantia.as_view(), name="garantia"),
    path('termos_de_uso/', views.informacoesTermosUso.as_view(), name="termos_de_uso"),
    path('politica_de_privacidade/', views.informacoesPoliticaPrivacidade.as_view(), name="politica_de_privacidade"),
    path('aviso_legal/', views.informacoesAvisoLegal.as_view(), name="aviso_legal"),
    path('documentacao/', views.informacoesDocumentacao.as_view(), name="documentacao"),
]

loja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('contato/', include('contato.urls')),
    path('aulas/', include('aulas.urls')),
    path('produto/', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('suporte/', include('suporte.urls')),
    path('conteudos/', include('conteudos.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),

    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),

    path('lista/', views.Lista.as_view(), name='lista'),

    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User


from django.conf import settings
import os
from PIL import Image
from django.db import models
from django.utils.text import slugify
from utils import utils


class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

pedido/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
# from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render
from produto.models import Variacao
from .models import Pedido, ItemPedido


from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from django.db.models import Q

from utils import utils




class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'


class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Seu carrinho está vazio.'
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)

            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
                carrinho[vid]['preco_quantitativo_promocional'] = estoque * \
                    preco_unt_promo

                error_msg_estoque = 'Estoque insuficiente para alguns '\
                    'produtos do seu carrinho. '\
                    'Reduzimos a quantidade desses produtos. Por favor, '\
                    'verifique quais produtos foram afetados a seguir.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )

                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = utils.cart_total_qtd(carrinho)
        valor_total_carrinho = utils.cart_totals(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )

        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del self.request.session['carrinho']

        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']

pedido/templates/pedido/detalhe.html
<!doctype html>
<html lang="pt-BR">

<head>
    {% include 'parciais/_head.html' %}
    <title>{% block titulo %}{% endblock %} Pedido - Detalhes</title>

    <style>
        :root{
            --green:#27ae60;
            --black:#192a56;
            --blue:#041562;
            --light-color:#666;
            --box-shadow:0 .5rem 1.5rem rgba(0,0,0,.1);
        }
        html{
            font-size: 62.5%;
            overflow-x: hidden;
            scroll-behavior: smooth;
            scroll-padding-top: 8rem;
        }
        
        ::-webkit-scrollbar{
            height: .5rem;
            width: 1rem;
        }
        
        ::-webkit-scrollbar-track{
            background-color: transparent;
        }
        
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
      
    </style>
</head>


{% load omfilters %}
{% load static %}

{% block conteudo %}

    {% include 'parciais/_menulateral.html' %}


    <div class="container" >


        <div class="row nav-produtos text-06 mt-3">

                <div class="col titulo-TipoProduto">

                    <i class='bx bx-layer iconePedidos icon'></i>
                    <span class="textos textoBranco tituloPage">Pedido | Detahe do pedido</span>
                </div>

                <div class="col btn-voltar">
                    <a class="bx bxs-arrow-from-right" href="{% url 'pedido:lista' %}"></a>
                </div>
        </div>

        <br><br><br><br><br><br>

        {% include 'parciais/_pedido.html' %}

    </div>

    <br><br><br><br><br><br><br><br><br>
    {% include 'parciais/_pagination.html' %}

{% endblock %}

pedido/templates/pedido/lista.html
{% load static%}
{% load omfilters %}


<html lang="pt-BR">

<head>

    {% include 'parciais/_head.html' %}
    <title>{% block titulo %}{% endblock %} Lista - Pedidos</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css'%}">
    <style>
        :root{
            --green:#27ae60;
            --black:#192a56;
            --blue:#041562;
            --light-color:#666;
            --box-shadow:0 .5rem 1.5rem rgba(0,0,0,.1);
        }
        html{
            font-size: 62.5%;
            overflow-x: hidden;
            scroll-behavior: smooth;
            scroll-padding-top: 8rem;
        }
        
        ::-webkit-scrollbar{
            height: .5rem;
            width: 1rem;
        }
        
        ::-webkit-scrollbar-track{
            background-color: transparent;
        }
        
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        .titulo-TipoProduto{
            display: block;
            text-align-last: initial;
        }
        @media screen and (min-width: 800px) {
    
            .titulo-TipoProduto{
                padding: 43px 0px 0px 0px;
            }

        }
        
      
    </style>
</head>


<style>
     @import url('https://fonts.googleapis.com/css2?family=Jua&display=swap');
     @import url('https://fonts.googleapis.com/css2?family=Codystar:wght@300;400&display=swap');
     @import url('https://fonts.googleapis.com/css2?family=Codystar:wght@300;400&family=Rampart+One&display=swap');
     @import url('https://fonts.googleapis.com/css2?family=Codystar:wght@300;400&family=Dancing+Script&family=Rampart+One&display=swap');

</style>




{% block conteudo %}


    {% include 'parciais/_menulateral.html' %}


     <div class="containerProdutoCarrinho">


        <div class="container" >

            <div class="row nav-produtos container text-06 mt-3">

                <div class="titulo-TipoProduto">
                    <i class='bx bx-layer iconePedidos icon'></i>
                    <span class="textos textoBranco tituloPage">Pedidos</span>
                </div>

            </div>



            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="titulo-TipoProduto">
                            <p class="titulo1 texto-amarelo">Lista de pedidos</p>
                            <br>
                            <p class="textos textoBranco">A baixo estão todos os seus pedidos de licença do software CheckApp</p>
                        </div>
                   
            

                        <br><br><br><br>


                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tr>
                                    <th scope="col">Pedido</th>
                                    <th scope="col">Total</th>
                                    <th scope="col">Qtd. Licenças</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Detalhes</th>
                                </tr>


                                {% for pedido in pedidos %}
                                <tr>
                                    <th scope="row">{{ pedido }}</td>
                                    <td>{{ pedido.total|formata_preco }}</td>
                                    <td>{{ pedido.qtd_total }}</td>
                                    <td>{{ pedido.get_status_display }}</td>
                                    <td>
                                        <a href="{% url 'pedido:detalhe' pedido.id %}">
                                            Ver <i class="fas fa-search-plus ml-2"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}


                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>

    <br><br><br><br><br><br><br><br><br>
    {% include 'parciais/_pagination.html' %}

{% endblock %}

pedido/templates/pedido/pagar.html
<!doctype html>
<html lang="pt-BR">

<head>
    {% include 'parciais/_head.html' %}
    <title>{% block titulo %}{% endblock %} Pagamento</title>
    <style>
        :root{
            --green:#27ae60;
            --black:#192a56;
            --blue:#041562;
            --light-color:#666;
            --box-shadow:0 .5rem 1.5rem rgba(0,0,0,.1);
        }
        html{
            font-size: 62.5%;
            overflow-x: hidden;
            scroll-behavior: smooth;
            scroll-padding-top: 8rem;
        }
        
        ::-webkit-scrollbar{
            height: .5rem;
            width: 1rem;
        }
        
        ::-webkit-scrollbar-track{
            background-color: transparent;
        }
        
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        @media screen and (max-width: 1000px){
            .navDetalhePedido{
                height: 300px !important;
            }
        }
        
      
    </style>
</head>



{% load omfilters %}
{% load static %}

{% block conteudo %}

    {% include 'parciais/_menulateral.html' %}

    <div class="container" >

        <div class="row nav-produtos text-06 mt-3">

            <div class="col titulo-TipoProduto">

                <i class='bx bx-dollar iconePedidos icon'></i>
                <span class="textos textoBranco tituloPage">Pagamento | Pedido n° {{ pedido.id }}</span>
            </div>

            <div class="col btn-voltar">

                    <a class="btn btn-Amarelo" href="{% url 'pedido:lista' %}"> Ver todos pedidos </a>
            </div>
        </div>
    </div>
    <br><br><br><br><br><br><br>


    <div class="container">

         <div class="container">
            {% include 'parciais/_pedido.html' %}
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <!--
        <div class="row mt-4">
            <div class="col">
                <a href="#" class="btn btn-amarelo">Pagar</a>
            </div>
        </div>
        -->
    </div>




{% endblock %}