home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homePage.as_view(), name="home"), 
    path('eventos/', views.listaEventos.as_view(), name="eventos"),
    path('projetos/', views.listaProjetos.as_view(), name="projetos"),
    path('sobre/', views.informacoesSobre.as_view(), name="sobre"),
    path('aulas/', views.informacoesAulas.as_view(), name="aulas"),
    path('contato/', views.informacoesContato, name="contato"),
    path('<slug>', views.detalhePost.as_view(), name="detalhe"),
    

    path('como_comprar/', views.informacoesComoComprar.as_view(), name="como_comprar"),
    path('pagamento_e_envio/', views.informacoesPagamentoEnvio.as_view(), name="pagamento_e_envio"),
    path('seguranca/', views.informacoesSeguranca.as_view(), name="seguranca"),
    path('frete/', views.informacoesFrete.as_view(), name="frete"),
    path('trocas_e_devolucoes/', views.informacoesTrocasDevulucoes.as_view(), name="trocas_e_devolucoes"),
    path('garantia/', views.informacoesGarantia.as_view(), name="garantia"),
    path('termos_de_uso/', views.informacoesTermosUso.as_view(), name="termos_de_uso"),
    path('politica_de_privacidade/', views.informacoesPoliticaPrivacidade.as_view(), name="politica_de_privacidade"),
    path('aviso_legal/', views.informacoesAvisoLegal.as_view(), name="aviso_legal"),
    path('documentacao/', views.informacoesDocumentacao.as_view(), name="documentacao"),
]

loja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('contato/', include('contato.urls')),
    path('aulas/', include('aulas.urls')),
    path('produto/', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('suporte/', include('suporte.urls')),
    path('conteudos/', include('conteudos.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),

    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),

    path('lista/', views.Lista.as_view(), name='lista'),

    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [

    path('', views.Criar.as_view(), name='criar'),

    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),

    path('login/', views.Login.as_view(), name='login'),

    path('logout/', views.Logout.as_view(), name='logout'),

    path('cadastrar/', views.Cadastrar.as_view(), name='cadastrar'),

    path('acesso/', views.Acesso.as_view(), name='acesso'),

]

produto/urls.py
from django.urls import path

from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),

    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),

    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name="adicionaraocarrinho"),

    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name="removerdocarrinho"),

    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),

    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),

    path('busca/', views.Busca.as_view(), name="busca"),

    path('produtos/', views.listaTodosProdutos.as_view(), name="produtos"),

    path('loja/', views.produtosLoja.as_view(), name="loja"),

    path('licencas/', views.listaLicencas.as_view(), name="licencas"),


]

produto/models.py
import os
from inspect import CORO_CREATED

from django.conf import settings
from django.db import models
from django.utils.text import slugify
from PIL import Image

from utils import utils


class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    mostrar = models.BooleanField(default=True, blank=True)

    imagem = models.ImageField(
        upload_to='produto_imagens/%Y/%m/', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promocional = models.FloatField(
        default=0, verbose_name='Preço Promo.')
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('C', 'Completo'),
            ('S', 'Simples'),
        )
    )

    def get_preco_formatado(self):
        return utils.formata_preco(self.preco_marketing)
    get_preco_formatado.short_description = 'Preço'

    def get_preco_promocional_formatado(self):
        return utils.formata_preco(self.preco_marketing_promocional)
    get_preco_promocional_formatado.short_description = 'Preço Promo.'

    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome


class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, blank=True, null=True)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

produto/forms.py
from django.forms.models import BaseInlineFormSet


class VariacaoObrigatoria(BaseInlineFormSet):
    def _construct_form(self, i, **kwargs):
        form = super(VariacaoObrigatoria, self)._construct_form(i, **kwargs)
        form.empty_permitted = False
        return form

produto/views.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from perfil.models import Perfil

from . import models


class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 10
    ordering = ['-id']

class Busca(ListaProdutos):
    def get_queryset(self, *args, **kwargs):
        termo = self.request.GET.get('termo') or self.request.session['termo']
        qs = super().get_queryset(*args, **kwargs)

        if not termo:
            return qs

        self.request.session['termo'] = termo

        qs = qs.filter(
            Q(nome__icontains=termo) |
            Q(descricao_curta__icontains=termo) |
            Q(descricao_longa__icontains=termo)
        )

        self.request.session.save()
        return qs


class DetalheProduto(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'


class AdicionarAoCarrinho(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            messages.error(
                self.request,
                'Produto não existe'
            )
            return redirect(http_referer)

        variacao = get_object_or_404(models.Variacao, id=variacao_id)
        variacao_estoque = variacao.estoque
        produto = variacao.produto

        produto_id = produto.id
        produto_nome = produto.nome
        variacao_nome = variacao.nome or ''
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem

        if imagem:
            imagem = imagem.name
        else:
            imagem = ''

        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Estoque insuficiente'
            )
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        carrinho = self.request.session['carrinho']

        if variacao_id in carrinho:
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            if variacao_estoque < quantidade_carrinho:
                messages.warning(
                    self.request,
                    f'Estoque insuficiente para {quantidade_carrinho}x no '
                    f'produto "{produto_nome}". Adicionamos {variacao_estoque}x '
                    f'no seu carrinho.'
                )
                quantidade_carrinho = variacao_estoque

            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * \
                quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * \
                quantidade_carrinho
        else:
            carrinho[variacao_id] = {
                'produto_id': produto_id,
                'produto_nome': produto_nome,
                'variacao_nome': variacao_nome,
                'variacao_id': variacao_id,
                'preco_unitario': preco_unitario,
                'preco_unitario_promocional': preco_unitario_promocional,
                'preco_quantitativo': preco_unitario,
                'preco_quantitativo_promocional': preco_unitario_promocional,
                'quantidade': 1,
                'slug': slug,
                'imagem': imagem,
            }

        self.request.session.save()

        messages.success(
            self.request,
            f'Produto {produto_nome} {variacao_nome} adicionado ao seu '
            f'carrinho {carrinho[variacao_id]["quantidade"]}x.'
        )

        return redirect(http_referer)


class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)

        carrinho = self.request.session['carrinho'][variacao_id]

        messages.success(
            self.request,
            f'Produto {carrinho["produto_nome"]} {carrinho["variacao_nome"]} '
            f'removido do seu carrinho.'
        )

        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        return redirect(http_referer)


class Carrinho(View):
    def get(self, *args, **kwargs):
        contexto = {
            'carrinho': self.request.session.get('carrinho', {})
        }

        return render(self.request, 'produto/carrinho.html', contexto)


class ResumoDaCompra(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        perfil = Perfil.objects.filter(usuario=self.request.user).exists()

        if not perfil:
            messages.error(
                self.request,
                'Usuário sem perfil.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio.'
            )
            return redirect('produto:lista')

        contexto = {
            'usuario': self.request.user,
            'carrinho': self.request.session['carrinho'],
        }

        return render(self.request, 'produto/resumodacompra.html', contexto)

class listaTodosProdutos(ListView):
    model = models.Produto
    template_name = 'produto/produtos.html'
    context_object_name = 'produtos'

class produtosLoja(ListView):
    model = models.Produto
    template_name = 'produto/loja.html'
    context_object_name = 'produtos'
    paginate_by = 50
    ordering = ['-id']

class listaLicencas(ListView):
    model = models.Produto
    template_name = 'produto/licencas.html'
    context_object_name = 'produtos'
    paginate_by = 50
    ordering = ['-id']

produto/templates/produto/carrinho.html
<!doctype html>
<html lang="pt-BR">

<head>
    {% include 'parciais/_head.html' %}
    <title>{% block titulo %}{% endblock %} CheckApp | Carrinho</title>
    <link rel="stylesheet" href="fonts/font-awesome.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">

    <style>
        :root{
            --green:#27ae60;
            --black:#192a56;
            --blue:#041562;
            --light-color:#666;
            --box-shadow:0 .5rem 1.5rem rgba(0,0,0,.1);
        }
        html{
            font-size: 62.5%;
            overflow-x: hidden;
            scroll-behavior: smooth;
            scroll-padding-top: 8rem;
        }
        
        ::-webkit-scrollbar{
            height: .5rem;
            width: 1rem;
        }
        
        ::-webkit-scrollbar-track{
            background-color: transparent;
        }
        
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        .navCarrinhoVazio{
            display: flex;
        }
        .icone-btb-LojaOnline{
            margin: 10px;
        }
        .usuarioLogado{
            display: flex;
            text-align: center;
        }
        .nomeUsuario{
            margin-left: 15px;
            font-size: 50px;
        }


        #header {
            width: 100%;
            position: fixed;
            top: 0;
            left: 0;
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -webkit-box-align: center;
                -ms-flex-align: center;
                    align-items: center;
            -webkit-box-pack: justify;
                -ms-flex-pack: justify;
                    justify-content: space-between;
            padding: 2rem 4rem;
            z-index: 1000;
        }

        #header .fa-hamburger {
            font-size: 4rem;
            z-index: 10000;
            color: #FFF200;
            cursor: pointer;
            display: none;
        }

        #header .logo img {
            height: 5rem;
        }

        #header nav ul {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -webkit-box-align: center;
                -ms-flex-align: center;
                    align-items: center;
            -ms-flex-pack: distribute;
                justify-content: space-around;
            list-style: none;
        }

        #header nav ul li {
            margin-right: 4rem;
            }

        #header nav ul li a {
            color: #fff;
            font-size: 2rem;
            }

        #header nav ul li a:hover {
            color: #FFF200;
            text-decoration: none;
            }

    
        .header-active {
            background: #333;
            height: 6rem;
            -webkit-box-shadow: .2rem 0 .5rem #000;
            box-shadow: .2rem 0 .5rem #000;
        }

        .header-active nav ul {
            margin: 0;
        }
        .logo{
            color: wheat;
            font-size: 100px;
        }
        .carrinhoVazio{
            padding: 0px 0px 0px 30px !important;
        }
        @media screen and (max-width: 800px) {
            .table tbody tr{
                display: inline-grid !important;
            }
            .container-conteudoCarrinho{
                padding: 0px 20px !important;
            }
            .btn-fazerCadastro{
                
            }
        }
        @media screen and (max-width: 600px) {
            
            .container-conteudoCarrinho{
                padding: 0px 0px !important;
            }
            .btn-fazerCadastro{
                width: 100% !important;
            }
        }
    </style>

</head>



{% load omfilters %}


{% block conteudo %}

    <div class="containerProdutoCarrinho container">

        {% include 'parciais/_menulateral.html' %}

        {% if carrinho %}


            <div class="container container-conteudoCarrinho" >

                <div class="row nav-produtos text-06 mt-3">

                    <div class="col titulo-TipoProduto">

                        <i class='bx bx-cart iconePedidos icon'></i>
                        <span class="textos textoBranco tituloPage">Carrinho </span>

                    </div>

                </div>
                <br><br><br>





                <div class="row container mt-3">
                    <div class="col">

                        {% include 'parciais/_carrinho.html' %}
                    </div>
                </div>



                <div class="col-lg container totalCarrinho ">
                    <p class='lead font-weight-bold'>Total da compra</p>

                    <div class='table-responsive'>
                        <table class="table-Carrinho table-ResumoCompra">
                            <tr class="tr-Table">

                                <td class="font-weight-bold precoTotal">{{ carrinho|cart_totals|formata_preco }}</td>
                            </tr>
                        </table>
                    </div>
                </div>



                <div class="row container mt-3">

                    <div class="col-lg btn-ActionCompra mt-auto">

                        {% if request.user.is_authenticated %}

                            <a class="btn btn-Amarelo" href="{% url 'produto:resumodacompra' %}">
                                Confirmar compra
                            </a>

                        {% else %}
                            <a class="btn btn-lg btn-block btn-danger btn-fazerCadastro" href="{% url 'perfil:acesso' %}">
                                FAÇA LOGIN PARA FINALIZAR O PEDIDO
                            </a>
                        {% endif %}

                    </div>


                </div>

                {% else %}


                <!-- header section starts -->

                

                <br><br><br><br><br><br><br><br><br>

                <div class="row container carrinhoVazio mt-3">
                    <div class="col">
                        <br><br><br>
                        <i class='bx bx-cart iconePedidos icon'></i>
                        <span class="textos textoBranco tituloPage">Carrinho </span>
                        
                        <br><br><br>

                        <div class="usuarioLogado">
                            <h3 class="titulo1 texto-amarelo">Olá, </h3>
                            <h3 class="textos textoBranco nomeUsuario">{{ user }}! </h3>
                        </div>
                        <br>
                        <br>
                        <br>
                        <br>
                        <h5 class="textos textoBranco"> Neste momento, seu carrinho ainda esta vazio</h5>
                        <br>
                        <br><br><br>

                        <a class="btn btn-Amarelo" href="{% url 'produto:loja' %}"> 
                            <i class='bx bx-store-alt icon icone-btb-LojaOnline'></i> Ver loja online 
                        
                        </a>
                    </div>
                </div>



            </div>

        </div>


    {% endif %}
    <br><br><br>





{% endblock %}

produto/templates/produto/detalhe.html
<!doctype html>
<html lang="pt-BR">

<head>
    <link rel="icon" href="media/imagens/icones/ico-checkapp.svg" >
    {% include 'parciais/_head.html' %}
    <title>{% block titulo %}{% endblock %} CheckApp | Detalhe produto</title>
    <style>
        :root{
            --green:#27ae60;
            --black:#192a56;
            --blue:#041562;
            --light-color:#666;
            --box-shadow:0 .5rem 1.5rem rgba(0,0,0,.1);
        }
        html{
            font-size: 62.5%;
            overflow-x: hidden;
            scroll-behavior: smooth;
            scroll-padding-top: 8rem;
        }
        
        ::-webkit-scrollbar{
            height: .5rem;
            width: 1rem;
        }
        
        ::-webkit-scrollbar-track{
            background-color: transparent;
        }
        
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        ::-webkit-scrollbar-thumb{
            background-color: #f3d600;
            border-radius: 5rem;
        }
        @media screen and (min-width: 800px) {
    
            .containerProduto{
                padding: 0px 20px;
            }
       
        }
        

        
      
    </style>
</head>

{% load omfilters %}

{% block conteudo %}

    {% include 'parciais/_menulateral.html' %}


    <div class="container containerProduto" >


        <div class="row nav-produtos text-06 mt-3">

            <div class="col titulo-TipoProduto">

                <i class='bx bx-cart iconePedidos icon'></i>
                <span class="textos textoBranco tituloPage">Carrinho | Produto</span>
            </div>

            <div class="col btn-voltar">
                <a class="bx bxs-arrow-from-right" href="{% url 'produto:licencas' %}"></a>
            </div>
        </div>

        <br><br><br><br><br><br>




        <div class="container containerProdutoLoja row">

            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        {% if produto.imagem %}
                        <img class="img-fluid" style="background-size: 80%" src="{{ produto.imagem.url }}">
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-lg cardProduto">
                <div class="card-adicionarProduto mt-4 mt-lg-0">
                    <h1 class="h2 textos">{{ produto.nome }}</h1>
                    <br>
                    <p class="lead textos2">{{ produto.descricao_curta }}</p>
                    <br>
                    
                    <p class="lead">
                        {% if produto.preco_marketing_promocional %}
                            <div class="preco-produto">
                                
                                <div class="preco-antigo">
                                    <p class="textos2">De</p>

                                    <span id="variation-preco" class=" textos2 precoAntigo lead product-old-price text-muted">
                                         {{ produto.preco_marketing|formata_preco }}
                                    </span>
                                </div>
                                <div class="preco-novo">
                                    <p class="textos2">por apenas</p>
                                    <span id="variation-preco-promocional" class="textos2 precoAtual lead product-price">
                                        {{ produto.preco_marketing_promocional|formata_preco }}
                                    </span>
                                </div>
                                

                                {% else %}
                                <span id="variation-preco" class="textos2 precoAtual lead product-price">
                                    {{ produto.preco_marketing|formata_preco }}
                                </span>
                            </div>
                        {% endif %}
                    </p>
                    <br>
                    <p class="textos2 textoQuantidade"> Selecione a quantidade:</p>

                    <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                       
                        <!--Seleção de varioações - Carrinho de compras -->
                        <div class="form-group adicaoProduto">

                            <select id="select-variacoes" name="vid" class="form-control formSelecao form-control-lg">
                                {% for variacao in produto.variacao_set.all %}

                                    {% if variacao.preco_promocional %}
                                        <option data-preco="{{ variacao.preco|formata_preco }}"
                                            data-preco-promocional="{{ variacao.preco_promocional|formata_preco }}"
                                            value="{{ variacao.id }}">
                                            {% if variacao.nome %}
                                                {{ variacao.nome }}
                                                {% else %}
                                                {{ variacao }}
                                            {% endif %}
                                        </option>

                                        {% else %}

                                        <option data-preco="{{ variacao.preco|formata_preco }}" value="{{ variacao.id }}">
                                            {% if variacao.nome %}
                                                {{ variacao.nome }}
                                                {% else %}
                                                {{ variacao }}
                                            {% endif %}
                                        </option>

                                    {% endif %}

                                {% endfor %}
                                
                            </select>
                            <button type="submit" class="btn btn-danger btn-lg btn-block">
                                <i class='bx bx-plus-medical'></i>
                            </button>
                        </div>


                        <!--Carrinho de compras -->


                        {% if request.session.carrinho %}
                            <div class="container containerQTDcarrinho">
                                <li class="nav-item">

                                    <a class="nav-link nav-linkCarrinho nav-cart-link active" href="{% url 'produto:carrinho' %}">

                                        <i class='bx bx-cart icon' ></i>

                                    </a>
                                    <!--Resumo do Carrinho de compras -->

                                    <div class="resumoCarrinho">

                                        <span class="nav-cart-count mr-1">
                                                <strong>Total  {{ request.session.carrinho|cart_totals }} </strong>
                                        </span>

                                        <span class="nav-cart-count mr-1">
                                            <strong>{{ request.session.carrinho|cart_total_qtd }} Produtos adicionados</strong>
                                        </span>
                                    </div>

                                </li>
                            </div>
                            <br>
                            <div class="text-left">
                                <a class="btn btn-Amarelo" href="{% url 'produto:carrinho' %}">Ver carrinho</a>   
                            </div>

                        {% endif %}
                    </form>
                </div>
            </div>
        </div>

        <div class="row row-detalhe-produto">
            <br>
            <h1 class="text-center"><strong>DESCRIÇÃO DO PRODUTO</strong></h1>

            <br>
            <br>
            <br>
            
            <h2 class="text-center">{{ produto.nome }}</h2>
            <br>
            <br>
            
            <h2 class="text-center">{{ produto.descricao_longa|linebreaks }}
            
           
        </div>

    </div>

{% endblock %}

produto/templates/produto/lista.html
{% extends 'base.html' %}
{% load omfilters %}

{% block titulo %}Produtos | {% endblock %}


{% block conteudo %}

<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in produtos %}

            <div class="card">

                {% if produto.imagem %}
                <a href="{% url 'produto:detalhe' produto.slug %}">
                    <img class="card-img-top" src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
                </a>
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ produto.nome }}</h5>
                    <p class="card-text">{{ produto.descricao_curta }}</p>
                    <div class="container product-price-block text-center">

                        {% if produto.preco_marketing_promocional %}
                        <span class="product-price">
                            {{ produto.preco_marketing_promocional|formata_preco }}
                        </span>
                        <span class="product-old-price text-muted">
                            {{ produto.preco_marketing|formata_preco }}
                        </span>
                        {% else %}
                        <span class="product-price">
                            {{ produto.preco_marketing|formata_preco }}
                        </span>
                        {% endif %}

                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href="{% url 'produto:detalhe' produto.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>

            {% endfor %}





        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        {% include 'parciais/_pagination.html' %}
    </div>
</div>

{% endblock %}